### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [xaizek/uncov#4]
I would like to point out that an identifier like “[`UNCOV__BUILDHISTORY_HPP__`](https://github.com/xaizek/uncov/blob/4934d1dad60649ed2b85afe3d851b32f30553ea4/src/BuildHistory.hpp#L17 "Update candidate")” [does not fit](https://wiki.sei.cmu.edu/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier#DCL51CPP.Donotdeclareordefineareservedidentifier-NoncompliantCodeExample%28HeaderGuard%29 "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by xaizek** [comment]
Thanks, I forgot to push 7b8cd9d.

**Comment by elfring** [comment]
Thanks for [your adjustment of affected include guards](https://github.com/xaizek/uncov/commit/7b8cd9d73b457e17466daa9a0a2ad538e5a5f0ab "Don't use double underscores in header guards").
